version: 2
jobs:
  build:
    docker:
      - image: transifex/pyenv-tox
    working_directory: /home/debian/transifex-python-library
    steps:
      - checkout

      - restore_cache:
          keys:
            - txlib_too-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
            - txlib_too-{{ checksum "circle.yml" }}
            - txlib_too-

      - run: |
          mkdir -p test-results
          tox -- --cov-report xml --junitxml=test-results/junit.xml

      - save_cache:
          key: txlib_too-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
          paths:
            - ~/.cache/pip
            - .tox

      - store_artifacts:
          path: test-results/

      - store_test_results:
          path: test-results/
